---
git_version: "2.7.2"

git_dependencies:
  - gcc 
  - curl-devel 
  - expat-devel 
  - gettext-devel 
  - openssl-devel 
  - zlib-devel 
  - perl-ExtUtils-MakeMaker

git_download_dir: "/home/vagrant" 