---
- hosts: localhost
  connection: local
  become: yes

  roles:
    - role: common
    - role: php-fpm
    - role: nginx
      nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "local.example.jp"
        root: "/var/www/html/example"
        index: "index.php index.html index.htm"
        error_page: "500 502 503 504  /50x.html"
        access_log: "/var/log/nginx/local.example.jp.access.log"
        error_log: "/var/log/nginx/local.example.jp.error.log"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "example.jp.conf"
        extra_parameters: |
          location ~ \.php$ {
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              fastcgi_pass unix:/var/run/php-fpm.sock;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              include fastcgi_params;
          }
          ssl_certificate     /etc/ssl/local.example.jp/server.crt;
          ssl_certificate_key /etc/ssl/local.example.jp/server.key;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
    # - { role: "mysql", mysql_version: "5.6.22"}
