---
- hosts: localhost
  connection: local
  become: yes

  roles:
    - role: common
    - role: php-fpm
    - role: nginx
      nginx_vhosts:
      - listen: "443 ssl http2"
        server_name: "local.example.jp"
        root: "/var/www/html/example/public"
        index: "index.php index.html index.htm"
        error_page: "500 502 503 504  /50x.html"
        access_log: "/var/log/nginx/local.example.jp.access.log"
        error_log: "/var/log/nginx/local.example.jp.error.log"
        state: "present"
        template: "{{ nginx_vhost_template }}"
        filename: "example.jp.conf"
        extra_parameters: |
          location / {
              if (-f $request_filename) {
                  expires 30d;
                  break;
              }
              if (!-e $request_filename) {
                  rewrite ^/(.*)$ /index.php/$1 last;
              }
          }
          location ~ [^/]\.php(/|$) {
              fastcgi_split_path_info ^(.+\.php)(/.+)$;
              if (!-f $document_root$fastcgi_script_name) {
                  return 404;
              }
              fastcgi_pass unix:/var/run/php-fpm.sock;
              fastcgi_index index.php;
              fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
              fastcgi_param  PATH_INFO $fastcgi_path_info;
              fastcgi_param  REQUEST_FILENAME  $request_filename;
              include fastcgi_params;
          }
          ssl_certificate     /etc/ssl/local.example.jp/server.crt;
          ssl_certificate_key /etc/ssl/local.example.jp/server.key;
          ssl_protocols       TLSv1.1 TLSv1.2;
          ssl_ciphers         HIGH:!aNULL:!MD5;
    - role: mysql
