---
- name: secure_pathに/usr/local/binを追加
  lineinfile: dest=/etc/sudoers state=present regexp='^Defaults    secure_path' line='Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'

- name: phpenvのインストール
  shell: curl -L https://raw.github.com/CHH/phpenv/master/bin/phpenv-install.sh | bash
  sudo: no

- name: bashファイルの追記
  lineinfile:
    dest: "~/.bashrc"
    line: "export PATH=$HOME/.phpenv/bin:$PATH"
  sudo: no

- lineinfile:
    dest: "~/.bashrc"
    line: eval "$(phpenv init -)"
  sudo: no

- name: pluginsディレクトリを作成
  file: path=~/.phpenv/plugins state=directory
  sudo: no

- name: php-buildをプラグインとしてインストール
  command: git clone git://github.com/php-build/php-build.git chdir=~/.phpenv/plugins
  sudo: no

- name: php依存パッケージをインストール
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
   - bison
   - libxml2
   - libxml2-devel
   - libxslt-devel
   - libtidy-devel
   - readline-devel
   - libpng
   - libpng-devel
   - libjpeg
   - libjpeg-devel

- name: re2cはrpmforgeから
  yum:
    name: re2c
    state: installed
    enablerepo: "rpmforge"

- name: libmcryptはepelから
  yum:
    name: "{{ item }}"
    state: installed
    enablerepo: "epel"
  with_items:
   - libmcrypt
   - libmcrypt-devel

- name: "php({{ php_version }})をインストール"
  shell: bash -lc "phpenv install {{ php_version }}" #"
  sudo: no

- name: 起動スクリプトをサービスに移動
  copy: src=/tmp/php-build/source/{{ php_version }}/sapi/fpm/init.d.php-fpm dest=/etc/init.d/php-fpm-{{ php_version }}

- name: パーミッション変更
  file: path=/etc/init.d/php-fpm-{{ php_version }} mode=755

- name: php-fpm.confを作成
  copy: src=/home/vagrant/.phpenv/versions/{{ php_version }}/etc/php-fpm.conf.default dest=/home/vagrant/.phpenv/versions/{{ php_version }}/etc/php-fpm.conf

- name: timezoneをAsia/Tokyoに変更
  lineinfile: dest=/home/vagrant/.phpenv/versions/{{ php_version }}/etc/php.ini state=present regexp='^;date.timezone' line='date.timezone=Asia/Tokyo'

- include: opcache.yml
  when: php_enable_opcache_configure

- name: "php-fpm-{{ php_version }}のchkconfigをONにする"
  service:
    name: "php-fpm-{{ php_version }}"
    state: started
    enabled: yes








