---
apache_enablerepo: "epel-httpd24"
apache_packages:
  - httpd24-httpd
  - httpd24-httpd-devel
  - httpd24-mod_ssl
  - openssl

apache_listen_port: 80
apache_listen_port_ssl: 443

apache_user: "apache"
apache_group: "apache"

# fastcgiからphpを利用するかどうか
apache_php_fpm: true

# vhostsファイルを生成するかどうか
apache_create_vhosts: true
# vhostsファイル名
apache_vhosts_filename: "vhosts.conf"

apache_global_vhost_settings: |
  DirectoryIndex index.php index.html

apache_vhosts: []
  # Additional properties: 'serveradmin, serveralias, extra_parameters'.
  # - servername: "local.dev"
    # documentroot: "/var/www/html"

apache_ssl_path: "/etc/httpd/conf/ssl.key"

apache_vhosts_ssl: []
  # Additional properties: 'serveradmin, extra_parameters'.
  # - servername: "local.dev",
  #   documentroot: "/var/www/html",
  #   certificate_file: "/path/to/certificate.crt",
  #   certificate_key_file: "/path/to/certificate.key",
  #   # Optional.
  #   certificate_chain_file: "/path/to/certificate_chain.crt"

apache_ignore_missing_ssl_certificate: true

apache_ssl_protocol: "All -SSLv2 -SSLv3"
apache_ssl_cipher_suite: "AES256+EECDH:AES256+EDH"

# Only used on Debian/Ubuntu.
apache_mods_enabled:
  - rewrite.load
  - ssl.load
apache_mods_disabled: []

# Set initial apache state. Recommended values: `started` or `stopped`
apache_state: started
