---
- name: pythonビルドの依存ライブラリのインストール xz bzip2-devel readline-devel sqlite-devel
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - xz
    - bzip2-devel
    - readline-devel
    - sqlite-devel

- name: pyenvのインストール
  git: repo=git://github.com/yyuu/pyenv.git dest=~/.pyenv
  become: no

- name: bashrcファイルの追記
  blockinfile:
    dest: "~/.bashrc"
    block: |
      export PYENV_ROOT="${HOME}/.pyenv"
      if [ -d "${PYENV_ROOT}" ]; then
          export PATH=${PYENV_ROOT}/bin:$PATH
          eval "$(pyenv init -)"
      fi
  become: no

- name: virtualenvのインストール
  git: repo=git://github.com/yyuu/pyenv-virtualenv.git dest=~/.pyenv/plugins/pyenv-virtualenv
  become: no
