---
- name: 既存のmysqlを削除
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - "mysql*"
    - "mariadb-libs"

- name: "MySQL5.7のrpmをインストール"
  yum:
    name: "http://dev.mysql.com/get/mysql57-community-release-el7-7.noarch.rpm"
    state: installed


- name: "MySQLをインストール"
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - "mysql "
    - "mysql-devel"
    - "mysql-server"
    - "mysql-utilities"

- name: MySQL-pythonをインストール
  yum:
    name: "MySQL-python"
    state: installed

- name: /etc/my.cnfを設置
  template:
    src: "mycnf.j2"
    dest: "/etc/my.cnf"
    owner: root
    group: root
    mode: 0644

- name: mysql初期化
  command: mysqld --user=mysql --initialize

- name: mysqlのchkconfigをONにする
  service: state=started name=mysqld

- name: デフォルトのランダムパスワードを確認
  shell: grep "A temporary password is generated" /var/log/mysqld.log | tr -s ' ' '\n' | tail -1
  register: root_initial_pswd

- name: ~/.my.cnfを配置
  template:
    src: ".my.cnf.j2"
    dest: "~/.my.cnf"
    owner: root
    group: root
    mode: 0644

- name: setup mysql root
  command: mysqladmin -u root password {{ root_initial_pswd.stdout }}

- name: デフォルトのrootのパスワードを変更
  mysql_user: name=root password={{mysql_root_pswd}}
